language: node_js
node_js:
  - "5.0"
sudo: false

env:
    - GULP="./node_modules/.bin/gulp"

script:
    - $GULP lint
    - '[ -z "$TRAVIS_PULL_REQUEST" ] && $GULP test'

cache:
    directories:
        - node_modules

addons:
  sauce_connect: true
